export const theme = {
  surface: "var(--surface)",
  paper: "var(--paper)",
  ink: "var(--ink)",

  ink88: "var(--ink-88)",
  ink85: "var(--ink-85)",
  ink8: "var(--ink-8)",
  ink75: "var(--ink-75)",
  ink72: "var(--ink-72)",
  ink65: "var(--ink-65)",
  ink6: "var(--ink-6)",
  ink55: "var(--ink-55)",
  ink5: "var(--ink-5)",
  ink48: "var(--ink-48)",
  ink45: "var(--ink-45)",
  ink42: "var(--ink-42)",
  ink38: "var(--ink-38)",
  ink35: "var(--ink-35)",
  ink32: "var(--ink-32)",
  ink3: "var(--ink-3)",
  ink28: "var(--ink-28)",

  inkBg04: "var(--ink-bg-04)",
  inkBg025: "var(--ink-bg-025)",
  inkBg02: "var(--ink-bg-02)",
  inkBg03: "var(--ink-bg-03)",
  inkBg05: "var(--ink-bg-05)",

  inkBorder1: "var(--ink-border-1)",
  inkBorder09: "var(--ink-border-09)",
  inkBorder08: "var(--ink-border-08)",
  inkBorder07: "var(--ink-border-07)",
  inkBorder06: "var(--ink-border-06)",
  inkBorder12: "var(--ink-border-12)",
  inkBorder16: "var(--ink-border-16)",

  moss: "var(--moss)",
  moss88: "var(--moss-88)",
  moss78: "var(--moss-78)",
  moss68: "var(--moss-68)",
  moss62: "var(--moss-62)",
  mossBg06: "var(--moss-bg-06)",
  mossBg09: "var(--moss-bg-09)",
  mossBorder16: "var(--moss-border-16)",
  mossBorder24: "var(--moss-border-24)",
  mossBorder38: "var(--moss-border-38)",

  plum: "var(--plum)",
  plum72: "var(--plum-72)",
  plumBg07: "var(--plum-bg-07)",
  plumBorder18: "var(--plum-border-18)",

  red88: "var(--red-88)",
  red85: "var(--red-85)",
  red9: "var(--red-9)",
  redBg08: "var(--red-bg-08)",
  redBg06: "var(--red-bg-06)",
  redBg05: "var(--red-bg-05)",
  redBorder25: "var(--red-border-25)",
  redBorder22: "var(--red-border-22)",
  redBorder18: "var(--red-border-18)",
  redBorder16: "var(--red-border-16)",
  redBorder14: "var(--red-border-14)",

} as const;

export const mono = { fontFamily: "var(--mono)" } as const;

export const labelStyles = {
  section: {
    display: "block",
    fontSize: 15,
    fontFamily: "var(--serif)",
    color: theme.moss,
    fontWeight: 600,
    letterSpacing: 0.1,
    marginBottom: 10,
  } as React.CSSProperties,
  field: {
    display: "block",
    fontSize: 12,
    ...mono,
    color: theme.ink72,
    fontWeight: 700,
    letterSpacing: 0.2,
    marginBottom: 10,
  } as React.CSSProperties,
  micro: {
    fontSize: 9,
    ...mono,
    letterSpacing: 0.8,
  } as React.CSSProperties,
} as const;
